
server:
  port: 2345

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/githubdata
    username: postgres
    password: shuxin
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #globally_quoted_identifiers: true

  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
